version: '3'

services:
  db:
    image: mariadb:10.5
    user: "1000:1000"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moneyprintergobrrr
      - MYSQL_PASSWORD=moneyprintergobrrr
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:6
    user: "1000:1000"
    restart: on-failure
    volumes:
      - "${APP_DATA_DIR}/data/redis:/data"

  web:
    image: nextcloud:21-apache
    # Currently needs to be run as root
    # https://github.com/nextcloud/docker/blob/05026b029d37fc5cd488d4a4a2a79480e39841ba/21.0/apache/entrypoint.sh#L53-L77
    # user: "1000:1000"
    restart: on-failure
    ports:
      - ${APP_NEXTCLOUD_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=moneyprintergobrrr
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_ADMIN_USER=umbrel
      # TODO: Make this dynamic, otherwise it's unsafe to share the onion address
      - NEXTCLOUD_ADMIN_PASSWORD=moneyprintergobrrr
      - NEXTCLOUD_TRUSTED_DOMAINS=umbrel.local:${APP_NEXTCLOUD_PORT} ${APP_HIDDEN_SERVICE}
    depends_on:
      - db
      - redis
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_IP

  cron:
    image: nextcloud:21-apache
    # Currently needs to be run as root
    # https://github.com/nextcloud/docker/blob/05026b029d37fc5cd488d4a4a2a79480e39841ba/21.0/apache/entrypoint.sh#L53-L77
    # user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
